### ISSUE TITLE
check the default selected option to be 'Management Plane'

### ISSUE THREAD

**Issue by josefree** [test-repo-billy/azure-rest-api-specs#2835]
statistically, 90% product has management plane APIs.  Shall we change the default selected type to be 'management plane'?
![image](https://user-images.githubusercontent.com/18413981/211990823-30147003-1767-42bb-bade-8c767de9eddd.png)

**Comment by honghr** [comment]
![image](https://user-images.githubusercontent.com/88764852/212237962-7b5068e3-4406-4a9e-af76-5aedc94a499a.png)
