### ISSUE TITLE
Typo in second step to create Mgmt Plane Release Plan

### ISSUE THREAD

**Issue by fengzhou-msft** [test-repo-billy/azure-rest-api-specs#2840]
<img width="976" alt="image" src="https://user-images.githubusercontent.com/55177366/211992859-e1c78a5b-13df-4062-adf6-184782234e51.png">

**Comment by lirenhe** [comment]
One more question, looks there is only one option of the release plan, why asking service team to select?

**Comment by live1206** [comment]
> One more question, looks there is only one option of the release plan, why asking service team to select?

There could be multiple options, if the user chooses to create both management and data plane.

**Comment by honghr** [comment]
![image](https://user-images.githubusercontent.com/88764852/212237690-af740aa1-aa0f-417e-a45d-2263580da66a.png)
