### ISSUE TITLE
Define service API tab color is confusing

### ISSUE THREAD

**Issue by ruowan** [test-repo-billy/azure-rest-api-specs#2841]
If I select "using cadl", the color is light.  For me the light color means inactive.  Is this behavior expected.

<img width="848" alt="image" src="https://user-images.githubusercontent.com/52271048/211992869-927286c9-c9ac-4c28-a865-8dd4b1c8038a.png">

**Comment by live1206** [comment]
Reverse this

**Comment by honghr** [comment]
![image](https://user-images.githubusercontent.com/88764852/212297351-3e2d7c10-e7ec-438e-8b1a-ff844e2b3d8e.png)
