### ISSUE TITLE
when adding user, the substitute of the user is not that meaningful

### ISSUE THREAD

**Issue by josefree** [test-repo-billy/azure-rest-api-specs#2842]
when adding user, the substitute of the user is not that meaningful, can be improved?
![image](https://user-images.githubusercontent.com/18413981/211992968-db14e752-4b50-4d7f-bd6e-30bba212a010.png)

**Comment by honghr** [comment]
The second row is user alias. These data are from office365 and we cannot control it.

**Comment by live1206** [comment]
Add caption for fields

**Comment by honghr** [comment]
![image](https://user-images.githubusercontent.com/88764852/212305122-b78d6504-057b-49b9-abb6-d9387b09d8d6.png)

Power apps cannot support that add caption in the dropdown list. Can we update the wording to tell user? @josefree @live1206

**Comment by honghr** [comment]
discussed with Josephine, agree to user above design.
