### ISSUE TITLE
[ux] remove hand cursor icon for mouse in welcome page of Management Plane API Readiness

### ISSUE THREAD

**Issue by archerzz** [test-repo-billy/azure-rest-api-specs#2843]
## Problem

It's quite confusing, since people may think they can do something with mouse, but actually they cannot.

![image](https://user-images.githubusercontent.com/4516/211993109-ca5ccfea-759e-4cd8-9005-a180649122a4.png)

**Comment by zzvswxy** [comment]
Management SDK Release app have the same question, so I want to know if there are any solution.

**Comment by live1206** [comment]
Remove checkbox

**Comment by zzvswxy** [comment]
Management SDk Release app done in Dev

**Comment by honghr** [comment]
![image](https://user-images.githubusercontent.com/88764852/212296903-c7b801fe-ac4a-4bea-b585-e0c60347f9af.png)
