### ISSUE TITLE
User search function can be improved

### ISSUE THREAD

**Issue by leniatgh** [test-repo-billy/azure-rest-api-specs#2844]
- [ ] Some invalid options can be hidden
![image](https://user-images.githubusercontent.com/7233663/211992851-e30b9eef-a9de-4696-8140-9b4d92635257.png)

- [ ] Cannot find user with fullname, e.g, "josephine qiu"
![image](https://user-images.githubusercontent.com/7233663/211992999-18ae7618-5933-475d-a7e0-9034022d82fe.png)

- [ ] When select user "A" to edit, the panel shows last user, instead of current user

**Comment by live1206** [comment]
I think the search only supports MS alias

cc @honghr

**Comment by honghr** [comment]
Yes, We only support alias search and this is from office365 datasource.
