### ISSUE TITLE
[ux] color theme for selected tab should be bright instead of fade-out

### ISSUE THREAD

**Issue by archerzz** [test-repo-billy/azure-rest-api-specs#2845]
## Problem

See the screen snpashot. In `Define Your Service APIs` page of `Management Plane API Readiness` app, the selected tab is using fade-out color theme. That's against intuition.

![image](https://user-images.githubusercontent.com/4516/211993620-a7577f25-ef12-4bda-8f11-1db1c1cf041f.png)

**Comment by live1206** [comment]
Duplicated with https://github.com/test-repo-billy/azure-rest-api-specs/issues/2841
