### ISSUE TITLE
Add a link here to API Spec pipeline support channel in teams

### ISSUE THREAD

**Issue by akning-ms** [test-repo-billy/azure-rest-api-specs#2846]
![image](https://user-images.githubusercontent.com/57385816/211993413-a6040a7e-0afc-45ea-962a-6d7d6de60969.png)

**Comment by live1206** [comment]
The support link is pointing to a form right now.
@josefree @raych1 Do you suggest we provide the teams channel here instead/as well?

**Comment by live1206** [comment]
Change the link from form to support channel: https://aka.ms/api-toolset/pipeline-online-support
