### ISSUE TITLE
not able to edit milestone owner

### ISSUE THREAD

**Issue by josefree** [test-repo-billy/azure-rest-api-specs#2847]
Keep seeing the error "user cannot be added..." no matter to edit milestone owner directly, or add the user as member

![image](https://user-images.githubusercontent.com/18413981/211993400-e7b48327-3809-4463-b351-18ccc25b45d1.png)
![image](https://user-images.githubusercontent.com/18413981/211993560-c2a954ce-30cc-434b-9c36-ac2b3c279828.png)

**Comment by live1206** [comment]
I think this is expected, as the error message says the selected user does not have access to the App.
@josefree I guess you wanted to search for "Haoran Hong"? 
And I think the search only supports MS alias.
I can assign it to people with permission as below:


![Image](https://user-images.githubusercontent.com/5196139/212228851-703c6e5e-9ea3-415a-b3a6-f8e7992d923c.png)

**Comment by live1206** [comment]
@honghr Add a help text to hint that search support MS Alias.

**Comment by josefree** [comment]
The selected user has not been authorized to visit the app.  Please ask the app admin for help.

**Comment by honghr** [comment]
![image](https://user-images.githubusercontent.com/88764852/212294912-2fdd4f54-69be-4329-91bf-b7582999d082.png)
