### ISSUE TITLE
[ux] associate button is not required if you can only associate one pr

### ISSUE THREAD

**Issue by archerzz** [test-repo-billy/azure-rest-api-specs#2848]
## Problem

I think we can incorporate the association function into `Next` button. Current UX design makes me thing I can associated more than one PR.

![image](https://user-images.githubusercontent.com/4516/211994192-69443f0e-e31a-47f6-9c79-9c9e0b2605c5.png)

**Comment by live1206** [comment]
But it still requires a trigger to associate the PR to the release plan, we do not know when the user has finished editing.

**Comment by live1206** [comment]
Postpone this to wait for further user feedback from service team
