### ISSUE TITLE
[ux] allow editing already submitted management plane api readiness check

### ISSUE THREAD

**Issue by archerzz** [test-repo-billy/azure-rest-api-specs#2850]
## Problem

If I made mistake in the middle of the process, I cannot go back and edit the form. Instead, I have to restart the whole process which is not user friendly.

**Comment by live1206** [comment]
Actually, re-activate a new PR to the release plan will reset the status of steps in API Readiness App.
Need @josefree to decide if this is enough.

**Comment by live1206** [comment]
@archerzz What action do you want to edit other than associate another PR?

**Comment by archerzz** [comment]
> @archerzz What action do you want to edit other than associate another PR?

Currently I just want to change the associated PR. Thanks.
