### ISSUE TITLE
color of activate tab item looks wired

### ISSUE THREAD

**Issue by changlong-liu** [test-repo-billy/azure-rest-api-specs#2852]
In below screen, the current active tab is "Using cadl", but the color of "Using cadl"is grey and makes me feel it's inactive.

![image](https://user-images.githubusercontent.com/59815250/211995522-4e0f040c-ee8f-485d-a524-06a403a206bb.png)

**Comment by live1206** [comment]
Duplicated with https://github.com/test-repo-billy/azure-rest-api-specs/issues/2841
