### ISSUE TITLE
No clear guidance on 'Generate SDK and Namespace Review'

### ISSUE THREAD

**Issue by lirenhe** [test-repo-billy/azure-rest-api-specs#2854]
1. Who will do the SDK and namespace review?  Do we expect service team to schedule review meetings?
2. What is the guidance to review SDK and Namespace?
3. What action to take if there are any feedbacks.
4. Is there any way we could get the go sdk package or at lease explain why the package is not there.
5. No api view for it?

**Comment by live1206** [comment]
Remove "and management library namespace review" from title and navigation panel.

**Comment by honghr** [comment]
![image](https://user-images.githubusercontent.com/88764852/212293480-c71b541e-4b20-4520-acc6-473dde371794.png)
