### ISSUE TITLE
How to start a workflow

### ISSUE THREAD

**Issue by akning-ms** [test-repo-billy/azure-rest-api-specs#2855]
![image](https://user-images.githubusercontent.com/57385816/211996597-75a4051c-e195-4db4-9d61-20f877e28e59.png)

Current our design is using start button in this welcome page which easy to ignore by user
Can we use any first click event like click checkbox or click next button to start a workflow?

**Comment by live1206** [comment]
Remove start button, activate as entering the App first time

**Comment by honghr** [comment]
1. Keep start button display and only jump to next page when user click.
2. Activate first step in page loading.
