### ISSUE TITLE
The checkbox in welcome page is unclickable.

### ISSUE THREAD

**Issue by ruowan** [test-repo-billy/azure-rest-api-specs#2856]
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/52271048/211997053-96fb8af7-f4e7-41d0-b54b-8a76437fe5d5.png">
The checkbox in welcome page is unclickable.

**Comment by fengzhou-msft** [comment]
I think it's by design to be unclickable, but the color should be faded, like API Readiness does:
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/55177366/211997732-4b8b58a6-1d3b-4b05-906c-5d4ceb0c80ec.png">

**Comment by live1206** [comment]
Related with https://github.com/test-repo-billy/azure-rest-api-specs/issues/2843

**Comment by zzvswxy** [comment]
done in dev, Current use readiness's solution.
