### ISSUE TITLE
Security Issue: hackers can change others' flow when having a workflow id

### ISSUE THREAD

**Issue by dw511214992** [test-repo-billy/azure-rest-api-specs#2857]
I can open other's flow when having the http link.

**Comment by live1206** [comment]
We can add a check of workflow and current user while loading API Readiness and SDK Release App.

**Comment by zzvswxy** [comment]
If we have a solution, assign this issue to me and haoran.

**Comment by zzvswxy** [comment]
Another thing, I think it's better only check this in Prod env. For this 'bug' is helpful in debug issues.

**Comment by live1206** [comment]
@zzvswxy @honghr 
We have a table called `SDK Release Workflow User`, where we store the user permission of workflows. There is a column called `System User`.
And during the loading of API readiness and SDK release App(for both management and data plane), we can check if  the current login user has permission to the corresponding workflow from the previous table.

**Comment by honghr** [comment]
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/88764852/212311173-dceb7f07-9cb3-42a1-8ee5-41a60a15744a.png)
