### ISSUE TITLE
Please suggest the next step when click 'Complete' in Signoff API Spec readiness

### ISSUE THREAD

**Issue by lirenhe** [test-repo-billy/azure-rest-api-specs#2859]
Currently, it will jump to the welcome page which is quite confusing.
It would be good to suggest the next step after completing the form

**Comment by live1206** [comment]
Similar to https://github.com/test-repo-billy/azure-rest-api-specs/issues/2865

**Comment by zzvswxy** [comment]
SDK Release App has the same question
