### ISSUE TITLE
Request suppression doesn't add comments

### ISSUE THREAD

**Issue by leniatgh** [test-repo-billy/azure-rest-api-specs#2860]
![image](https://user-images.githubusercontent.com/7233663/211998491-73525f13-e402-407b-91b6-d783dee46033.png)
It shows success, but no comments found in PR

![image](https://user-images.githubusercontent.com/7233663/211998607-904ab423-851e-4e60-8641-c617c7f08007.png)

**Comment by leniatgh** [comment]
Tried to add "Approved-ModelValidation" label manually, but the status in PowerApps is still Failure

**Comment by live1206** [comment]
> Tried to add "Approved-ModelValidation" label manually, but the status in PowerApps is still Failure

The status does not take consideration of "Approved-ModelValidation" label. Right now, we only check label "CI-failure" to get the correct summary status in the signoff page. 

@josefree Do you think we should set the status in the "Validation Errors" page to "Success" as well?

**Comment by live1206** [comment]
@honghr Could you check the run history of the flow to add comment to PR if there is any failure?

**Comment by live1206** [comment]
Add approve label status.

**Comment by honghr** [comment]
![image](https://user-images.githubusercontent.com/88764852/212304573-b772e36c-a4fe-4ab4-bae4-c501a17d88d2.png)
