### ISSUE TITLE
Can 'Expedcted Release Date' to be empty in SDK release App

### ISSUE THREAD

**Issue by lirenhe** [test-repo-billy/azure-rest-api-specs#2861]
The system does not require me to provide that date so do we have a default value?

![image](https://user-images.githubusercontent.com/9100546/211999017-ba40a888-1ea6-4542-bd61-8a77ee8cca0b.png)

**Comment by zzvswxy** [comment]
I think it's the same issues  https://github.com/test-repo-billy/azure-rest-api-specs/issues/2869
We did have a default value, it's the first value of release train. But read permission is missing for table SDK Release Train in PPE env. So you can get the value.
It fixed now.
