### ISSUE TITLE
Confirming PR status can be automated

### ISSUE THREAD

**Issue by leniatgh** [test-repo-billy/azure-rest-api-specs#2862]
![image](https://user-images.githubusercontent.com/7233663/211999230-d6272bf0-3b58-4a10-b0fd-29c7ec7321e5.png)

**Comment by zzvswxy** [comment]
It can be automated. @josefree  Do we change it?

**Comment by live1206** [comment]
Change the confirmation of PR to notification/error

**Comment by zzvswxy** [comment]
done in dev
