### ISSUE TITLE
add label of the field

### ISSUE THREAD

**Issue by josefree** [test-repo-billy/azure-rest-api-specs#2864]
please add text label of the field. Or it will be a little bit odd.  the PR link text should be [PR#] + [PR title]
![image](https://user-images.githubusercontent.com/18413981/211999411-d531cf4d-bc15-49a4-a450-8f9fb4e4f0e2.png)

**Comment by honghr** [comment]
![image](https://user-images.githubusercontent.com/88764852/212233368-a62a01b3-9832-4b71-bb65-4fe55dd4f937.png)
