### ISSUE TITLE
after API spec signoff 'Complete', it goes back to Welcome blade with 'start' lightened up

### ISSUE THREAD

**Issue by josefree** [test-repo-billy/azure-rest-api-specs#2865]
After clicking 'Complete' in API spec signoff blade, it goes back to Welcome blade with 'start' lightened up. The expectation is to stay in the API Spec signoff blade with 'Complete' to be greyed.  When switching back to previous blades, the buttons of 'Start' and 'Next' should be all greyed as well. 

![image](https://user-images.githubusercontent.com/18413981/211999871-c5b94ddd-e92a-4047-a225-93ebd160407e.png)

**Comment by zzvswxy** [comment]
But when user didn't meet the required condition, the Complete button is also greyed. It may confuse the user.

**Comment by zzvswxy** [comment]
click Complete button. The button should be grey and all next button be grey. 
CC @honghr

**Comment by zzvswxy** [comment]
Management SDk Release app done in dev

**Comment by honghr** [comment]
fixed in management plane api readiness app
