### ISSUE TITLE
Can not see release train info

### ISSUE THREAD

**Issue by tadelesh** [test-repo-billy/azure-rest-api-specs#2869]
![Screenshot_20230112_025847](https://user-images.githubusercontent.com/1726438/212001422-e45ca5f0-7b3f-4aa6-b48c-bc72b5ad2e61.png)
![Screenshot_20230112_030718](https://user-images.githubusercontent.com/1726438/212001426-23b416f5-8989-428f-8c2e-2b10bea0739f.png)

Microsoft Edge
Version 108.0.1462.76 (Official build) (64-bit)
Chrome is up to date
Version 109.0.5414.75 (Official Build) (64-bit)

**Comment by live1206** [comment]
Able to re-produce this with Firefox private mode using service account.
I tend to think this is a bug in SDK release planner, we failed to load the data from dataverse somehow.
cc @dw511214992 @zzvswxy

**Comment by live1206** [comment]
Read permission is missing for table `SDK Release Train`, added now.
