### ISSUE TITLE
Difference experience of inputting PR

### ISSUE THREAD

**Issue by tadelesh** [test-repo-billy/azure-rest-api-specs#2870]
![Screenshot_20230112_022154](https://user-images.githubusercontent.com/1726438/212001608-c6145a92-93b5-4323-a0e9-138f8e4c2995.png)
![Screenshot_20230112_025917](https://user-images.githubusercontent.com/1726438/212001624-74140e5d-e6aa-4d04-a872-a977b1f2b696.png)

**Comment by live1206** [comment]
@josefree Shall we follow the same pattern to fix the prefix of URL and let user just input the PR number?
