### ISSUE TITLE
One typo in SDK release page

### ISSUE THREAD

**Issue by tadelesh** [test-repo-billy/azure-rest-api-specs#2872]
![Screenshot_20230112_025430](https://user-images.githubusercontent.com/1726438/212001822-d2d0b0ef-a153-4735-9c94-fa7cff3469ad.png)

**Comment by zzvswxy** [comment]
Hi @josefree  , do you have any suggestion?

**Comment by live1206** [comment]
Just change `if` to `is`? This is a grammar error in the sentence.
