### ISSUE TITLE
No APIView for dotnet mgmt SDK

### ISSUE THREAD

**Issue by lirenhe** [test-repo-billy/azure-rest-api-specs#2876]
How can i get the APIView for it?

![image](https://user-images.githubusercontent.com/9100546/212007629-caef7d07-e1fd-42ae-ae00-038307c16504.png)

**Comment by zzvswxy** [comment]
We can get .Net apiview in Prod env. For this bugbash use 'openapi-env-test' sdk repo owner. So we can't trigger CI bot for apiview.
