### ISSUE TITLE
Failed to load readme file path

### ISSUE THREAD

**Issue by live1206** [test-repo-billy/azure-rest-api-specs#2878]
Tested with service account swagger@microsoft.com, failed to load readme file path in SDK Release App
<img width="883" alt="image" src="https://user-images.githubusercontent.com/5196139/212056998-4165ab0d-4051-4ee1-a9a9-9e2f9332c8ba.png">

**Comment by zzvswxy** [comment]
From now, I can use onchange property in input controller to update the default tag. But I don't know where to store the result. If it's ok to save default tag in 'SDK Release Workflow' table?

**Comment by live1206** [comment]
But should the read me path be filled for this PR in the first place?

**Comment by zzvswxy** [comment]
Yes, forget the issue don't show default readme file path. I will try to recurrence the issue.

**Comment by zzvswxy** [comment]
![image](https://user-images.githubusercontent.com/20081898/212230931-0441d868-5569-4826-bc0d-21973e3e9656.png)
 can you link the pr? can't find it in test-repo-billy

**Comment by zzvswxy** [comment]
the service account‘s connection has expired
