### ISSUE TITLE
crash when ask with context

### ISSUE THREAD

**Issue by tadelesh** [test-repo-billy/azure-rest-api-specs#3073]
https://teams.microsoft.com/l/message/19:jUMcWxaJkf9pgoBDdXtXj0h6KWIjZdE-gNHX8-n0a-I1@thread.tacv2/1698391757139?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=7aaec338-7ae4-4fbe-abbc-1341dc20f4d0&parentMessageId=1698391757139&teamName=SDK-Bot-Testing&channelName=General&createdTime=1698391757139&allowXTenantAccess=false

![image](https://github.com/test-repo-billy/azure-rest-api-specs/assets/1726438/3fe75194-5502-459d-928a-3b652919c400)

**Comment by raych1** [comment]
Same issue with https://github.com/test-repo-billy/azure-rest-api-specs/issues/3077
The input is white spaces.
